services:
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./go:/go/src
  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    env_file:
      - ./docker/postgres/.env
